version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ./../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: imretot/foodgram_backend
    env_file: ./../.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: imretot/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: imretot/foodgram_infra
    volumes:
      - static:/staticfiles/
      - media:/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    ports:
      - 8000:80