# Generated by Django 4.2.4 on 2023-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('мл', 'мл'), ('л', 'л'), ('шт', 'шт'), ('ст. л.', 'ст. л.'), ('д. л.', 'д. л.'), ('ч. л.', 'ч. л.')], max_length=200),
        ),
    ]
