# Generated by Django 4.2.4 on 2023-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('кг', 'кг'), ('г', 'г'), ('мл', 'мл'), ('л', 'л'), ('шт.', 'шт.'), ('ст. л.', 'ст. л.'), ('д. л.', 'д. л.'), ('ч. л.', 'ч. л.')], max_length=200, null=True),
        ),
    ]
