# Generated by Django 4.2.4 on 2023-08-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('кг', 'кг'), ('г', 'г'), ('мл', 'мл'), ('л', 'л'), ('шт.', 'шт.'), ('ст. л.', 'ст. л.'), ('д. л.', 'д. л.'), ('ч. л.', 'ч. л.')], max_length=200, null=True),
        ),
    ]
